### ISSUE TITLE
Offline-Docs testing

### ISSUE THREAD

**Issue by aleiner** [rancherfederal/carbide-charts#9]
In my first attempt, when I modified the downstream cluster global repository, it caused a new node to be spun up.  It did set the repository up on my existing node (after a rke2-restart), but then when it tried to pull a new etcd pod, it failed to find one in your registry. 
 
![image](https://user-images.githubusercontent.com/104371562/215774824-5734216d-28a5-47d3-901c-862a96b464f3.png)

With the registry setting all messed up, that new node wouldn’t come up cleanly, so I abandoned it all together.
 
On my other downstream cluster, instead of creating a global registry, I just added a second registry to that individual node (one node cluster) via registries.yaml. 
 
Once the containers all came up, the following links didn’t work:
Carbide-Offline-Docs – Coming Soon
Elemental-Offline-Docs – Coming Soon
Harvester-Offline-Docs – 503, ServiceUnavailable
Hauler-Offline-Docs – 404, services not found
NeuVector-Offline-Docs – 404, services not found
Rancher-Offline-Docs – Coming Soon
 
Here’s the commands I ran to get this to work:
 
yum install -y git
curl [https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fhelm%2Fhelm%2Fmaster%2Fscripts%2Fget-helm-3&data=05%7C01%7CAdam.Leiner%40rancherfederal.com%7C706dd76edcff42c1ab5108db0335baaf%7C33a80c43c6db4af6ab48af1b788748be%7C0%7C0%7C638107301549608780%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pWiY7wJhfFvLjCVLFyE7IFyIDRv2Dwhl9%2F%2B7ljY02F8%3D&reserved=0) | bash
 
cp ssh key (id_rsa)
git clone [git@github.com:rancherfederal/carbide-charts.git](mailto:git@github.com:rancherfederal/carbide-charts.git)
 
cd carbide-charts
#Need to specify namespace as carbide-system doesn't exist
helm upgrade --install offline-docs ./charts/offline-docs/ -n carbide-system --create-namespace
 
#registries.yaml:
configs:
"rgcrprod.azurecr.us":
   auth:
     username: internal-tester-read
     password: <insert super-secret password here>

**Comment by atoy3731** [comment]
Hi @aleiner .. Couple questions so I can dive in:

1. to confirm, this was a pre-existing Rancher-provisioned RKE2 cluster that you were porting over to Carbide images?
2. What version of RKE2 was running on the cluster?
3. Were you able to SSH into the bad cluster's node and check the `registries.yaml` config(s) in `/etc/rancher/rke2` and `/etc/rancher/agent` by chance?

**Comment by aleiner** [comment]
1.  I had an existing Rancher v2.6.9 instance setup with two Rancher-provisioned, single node downstream clusters.
2. All nodes were running RKE2 v1.23.14+rke2r1.
3. I had initially checked /etc/rancher/rke2/registries.yaml after making the change in the Rancher UI, and noticed the file was still empty.  I restarted the rke2-server service, and the registries.yaml file updated to:


`{"configs":{"rgcrprod.azurecr.us":{"auth":{"username":"internal-tester-read","password":"<password>","auth":"","identity_token":""},"tls":null}},"mirrors":null}`
